version: '2'

services:
  orion:
    container_name: orion
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/srv/orion/data
      - ./log:/srv/orion/log
      - ./temp:/srv/orion/temp