<?php

namespace App\Bot;

use App\Config\CredentialsLoader;
use Discord\Builders\CommandBuilder;
use Discord\Builders\MessageBuilder;
use Discord\Discord;
use Discord\Parts\Channel\Message;
use Discord\Parts\Interactions\Command\Command;
use Discord\Parts\Interactions\Command\Option;
use Discord\Parts\Interactions\Interaction;
use Discord\WebSockets\Event;

class SteamBot
{
    private Discord $discord;

    public function run(): void
    {
        $credentials = CredentialsLoader::load();

        $this->discord = new Discord(['token' => $credentials->getToken()]);

        $this->discord->on('ready', static function(Discord $discord) {
            echo 'Bot is ready!' . PHP_EOL;

//            $discord->on(Event::MESSAGE_CREATE, static function(Message $message, Discord $discord) {
//                echo "{$message->author->username}: {$message->content}" . PHP_EOL;
//            });

            $builder = CommandBuilder::new()
                ->setName('ping')
                ->setDescription('Pong!');

            $builder->addOption(
                (new Option($discord))
                    ->setName('game')
                    ->setDescription('Game Name/Id')
                    ->setType(Option::STRING)
                    ->setRequired(true)
            );

            $discord->application->commands->save(new Command($discord, $builder->toArray()));

            $discord->listenCommand('ping', function(Interaction $interaction) {
//                var_dump($interaction->data->options['game']->value);
//                $interaction->respondWithMessage(MessageBuilder::new()->setContent('Pong!'));

                $builder = MessageBuilder::new();

                $builder->addEmbed([
                    'type' => 'rich',
                    'title' => 'Battlefield 2042',
                    'description' => '',
                    'colors' => '0x70e814',
                    'fields' => [
                        [
                            'name' => 'Playing',
                            'value' => '2000 players',
                            'inline' => true,
                        ],
                        [
                            'name' => 'Release date',
                            'value' => '26. lis 2022',
                            'inline' => true,
                        ]
                    ],
                    'thumbnail' => [
                        'url' => 'https://cdn.cloudflare.steamstatic.com/steam/apps/1517290/capsule_184x69.jpg'
                    ],
                    'footer' => [
                        'text' => 'Generated by Orion'
                    ]
                ]);

                $interaction->respondWithMessage($builder);

//                [
//    {
//        "type": "rich",
//      "title": `Battlefield 2042`,
//      "description": "",
//      "color": 0x70e814,
//      "fields": [
//        {
//            "name": `Playing`,
//          "value": `2000 players `,
//          "inline": true
//        },
//        {
//            "name": `Release date`,
//          "value": `26. Lis 2022`,
//          "inline": true
//        }
//      ],
//      "thumbnail": {
//        "url": `https:\\/\\/cdn.cloudflare.steamstatic.com\\/steam\\/apps\\/1517290\\/capsule_184x69.jpg`,
//        "height": 0,
//        "width": 0
//      },
//      "footer": {
//        "text": `Generated by Orion`
//      }
//    }
//  ]
            });
        });

        $this->discord->run();
    }
}